export enum NEWS_ACTION_TYPES {
  SET_NEWS = 'SET_NEWS',
  SET_NEWS_ERROR = 'SET_NEWS_ERROR',
  GET_NEWS = 'GET_NEWS',
}

export enum OVERVIEW_ACTION_TYPES {
  SET_OVERVIEW = 'SET_OVERVIEW',
  SET_OVERVIEW_ERROR = 'SET_OVERVIEW_ERROR',
  GET_OVERVIEW = 'GET_OVERVIEW',
}
