export enum NEWS_ACTIONS_TYPES {
  SET_NEWS = 'SET_NEWS',
  GET_NEWS = 'GET_NEWS',
  SET_NEWS_ERROR = 'SET_NEWS_ERROR',
}

export enum OVERVIEW_ACTIONS_TYPES {
  SET_OVERVIEW = 'SET_OVERVIEW',
  GET_OVERVIEW = 'GET_OVERVIEW',
  SET_OVERVIEW_ERROR = 'SET_OVERVIEW_ERROR',
}

export enum PEERS_ACTIONS_TYPES {
  SET_TOP_PEERS = 'SET_TOP_PEERS',
  GET_TOP_PEERS = 'GET_TOP_PEERS',
  SET_TOP_PEERS_ERROR = 'SET_TOP_PEERS_ERROR',
}

export enum KEY_STATS_ACTIONS_TYPES {
  SET_KEY_STATS = 'SET_KEY_STATS',
  GET_KEY_STATS = 'GET_KEY_STATS',
  SET_KEY_STATS_ERROR = 'SET_KEY_STATS_ERROR',
}

export enum QUOTE_ACTIONS_TYPES {
  SET_QUOTE = 'SET_QUOTE',
  GET_QUOTE = 'GET_QUOTE',
  SET_QUOTE_ERROR = 'SET_QUOTE_ERROR',
}

export enum TIME_SERIES_ACTIONS_TYPES {
  SET_TIME_SERIES = 'SET_TIME_SERIES',
  GET_TIME_SERIES = 'GET_TIME_SERIES',
  SET_TIME_SERIES_ERROR = 'SET_TIME_SERIES_ERROR',
}

export enum SEARCH_ACTIONS_TYPES {
  SEARCH = 'SEARCH',
  SET_SEARCH_ERROR = 'SET_SEARCH_ERROR',
}
