import { isPartOf } from './common-typeguard';

export const isQuote = (testedObject: any): boolean => {
  const quoteProperties = [
    'symbol',
    'companyName',
    'calculationPrice',
    'open',
    'openTime',
    'close',
    'closeTime',
    'high',
    'low',
    'latestPrice',
    'latestSource',
    'latestTime',
    'latestUpdate',
    'latestVolume',
    'iexRealTimePrice',
    'iexRealTimeSize',
    'iexLastUpdated',
    'delayedPrice',
    'delayedPriceTime',
    'extendedPrice',
    'extendedChange',
    'extendedChangePercent',
    'extendedPriceTime',
    'previousClose',
    'change',
    'changePercent',
    'iexMarketPercent',
    'iexVolume',
    'avgTotalVolume',
    'iexBidPrice',
    'iexBidSize',
    'iexAskPrice',
    'iexAskSize',
    'marketCap',
    'peRatio',
    'week52High',
    'week52Low',
    'ytdChange',
  ];
  return isPartOf(quoteProperties, testedObject);
};
